### ISSUE TITLE
解锁应用网格图标导致启动器崩溃 

### ISSUE THREAD

**Issue by AadilGillani** [1767523953/MiuiHome#14]
启用解锁应用程序图标网格后，启动器崩溃并且无法工作，直到我禁用该选项

我正在使用谷歌翻译来写这条消息，因为我不会中文我可以用英文或中文写吗？

感谢您创建此模组，因为这是目前正在与 customiuizer 一起更新的 MI 最佳模组之一

**Comment by 1767523953** [comment]
Sure, you can write in English.
Can you give me the log of the crash?

**Comment by AadilGillani** [comment]
> Sure, you can write in English.
> Can you give me the log of the crash?

Here you go I couldn't find any option to attach files in GitHub:

https://drive.google.com/file/d/1CKAFliKQqvQge50Ao1Pf2Ou0FGZLkBXO/view?usp=drivesdk

**Comment by AadilGillani** [comment]
> Sure, you can write in English.
> Can you give me the log of the crash?


I guess this is the main the error I hope someday I become intelligent enough to understand this :( :

FATAL EXCEPTION: launcher-loader
Process: com.miui.home, PID: 10230
android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 1802 SQLITE_IOERR_FSTAT)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(Unknown Source:92)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(Unknown Source:41)
	at android.database.sqlite.SQLiteQuery.fillWindow(Unknown Source:28)
	at android.database.sqlite.SQLiteCursor.fillWindow(Unknown Source:44)
	at android.database.sqlite.SQLiteCursor.getCount(Unknown Source:6)
	at android.content.ContentResolver.query(Unknown Source:178)
	at android.content.ContentResolver.query(Unknown Source:4)
	at android.content.ContentResolver.query(Unknown Source:12)
	at com.miui.home.launcher.ScreenUtils.findActivities2Id(Unknown Source:41)
	at com.miui.home.launcher.AllAppsList.addPackage(Unknown Source:18)
	at com.miui.home.launcher.AllAppsList.updatePackage(Unknown Source:298)
	at com.miui.home.launcher.AllAppsList.updatePackage(Unknown Source:6)
	at com.miui.home.launcher.LauncherModel$LoaderTask.loadAndBindMissingIcons(Unknown Source:225)
	at com.miui.home.launcher.LauncherModel$LoaderTask.run(Unknown Source:802)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loop(Unknown Source:242)
	at android.os.HandlerThread.run(Unknown Source:28)

**Comment by 1767523953** [comment]
> > Sure, you can write in English.
> > Can you give me the log of the crash?
> 
> Here you go I couldn't find any option to attach files in GitHub:
> 
> https://drive.google.com/file/d/1CKAFliKQqvQge50Ao1Pf2Ou0FGZLkBXO/view?usp=drivesdk

I don't have permission to access

**Comment by 1767523953** [comment]
> > Sure, you can write in English.
> > Can you give me the log of the crash?
> 
> I guess this is the main the error I hope someday I become intelligent enough to understand this :( :
> 
> FATAL EXCEPTION: launcher-loader
> Process: com.miui.home, PID: 10230
> android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 1802 SQLITE_IOERR_FSTAT)
> at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
> at android.database.sqlite.SQLiteConnection.executeForCursorWindow(Unknown Source:92)
> at android.database.sqlite.SQLiteSession.executeForCursorWindow(Unknown Source:41)
> at android.database.sqlite.SQLiteQuery.fillWindow(Unknown Source:28)
> at android.database.sqlite.SQLiteCursor.fillWindow(Unknown Source:44)
> at android.database.sqlite.SQLiteCursor.getCount(Unknown Source:6)
> at android.content.ContentResolver.query(Unknown Source:178)
> at android.content.ContentResolver.query(Unknown Source:4)
> at android.content.ContentResolver.query(Unknown Source:12)
> at com.miui.home.launcher.ScreenUtils.findActivities2Id(Unknown Source:41)
> at com.miui.home.launcher.AllAppsList.addPackage(Unknown Source:18)
> at com.miui.home.launcher.AllAppsList.updatePackage(Unknown Source:298)
> at com.miui.home.launcher.AllAppsList.updatePackage(Unknown Source:6)
> at com.miui.home.launcher.LauncherModel$LoaderTask.loadAndBindMissingIcons(Unknown Source:225)
> at com.miui.home.launcher.LauncherModel$LoaderTask.run(Unknown Source:802)
> at android.os.Handler.handleCallback(Unknown Source:2)
> at android.os.Handler.dispatchMessage(Unknown Source:4)
> at android.os.Looper.loop(Unknown Source:242)
> at android.os.HandlerThread.run(Unknown Source:28)

Following the log, this error wasn't made by the module.

**Comment by AadilGillani** [comment]
> > > Sure, you can write in English.
> > > Can you give me the log of the crash?
> > 
> > Here you go I couldn't find any option to attach files in GitHub:
> > 
> > https://drive.google.com/file/d/1CKAFliKQqvQge50Ao1Pf2Ou0FGZLkBXO/view?usp=drivesdk
> 
> I don't have permission to access
Updated the permission sorry for this

**Comment by AadilGillani** [comment]
> > > Sure, you can write in English.
> > > Can you give me the log of the crash?
> > 
> > I guess this is the main the error I hope someday I become intelligent enough to understand this :( :
> > 
> > FATAL EXCEPTION: launcher-loader
> > Process: com.miui.home, PID: 10230
> > android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 1802 SQLITE_IOERR_FSTAT)
> > at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
> > at android.database.sqlite.SQLiteConnection.executeForCursorWindow(Unknown Source:92)
> > at android.database.sqlite.SQLiteSession.executeForCursorWindow(Unknown Source:41)
> > at android.database.sqlite.SQLiteQuery.fillWindow(Unknown Source:28)
> > at android.database.sqlite.SQLiteCursor.fillWindow(Unknown Source:44)
> > at android.database.sqlite.SQLiteCursor.getCount(Unknown Source:6)
> > at android.content.ContentResolver.query(Unknown Source:178)
> > at android.content.ContentResolver.query(Unknown Source:4)
> > at android.content.ContentResolver.query(Unknown Source:12)
> > at com.miui.home.launcher.ScreenUtils.findActivities2Id(Unknown Source:41)
> > at com.miui.home.launcher.AllAppsList.addPackage(Unknown Source:18)
> > at com.miui.home.launcher.AllAppsList.updatePackage(Unknown Source:298)
> > at com.miui.home.launcher.AllAppsList.updatePackage(Unknown Source:6)
> > at com.miui.home.launcher.LauncherModel$LoaderTask.loadAndBindMissingIcons(Unknown Source:225)
> > at com.miui.home.launcher.LauncherModel$LoaderTask.run(Unknown Source:802)
> > at android.os.Handler.handleCallback(Unknown Source:2)
> > at android.os.Handler.dispatchMessage(Unknown Source:4)
> > at android.os.Looper.loop(Unknown Source:242)
> > at android.os.HandlerThread.run(Unknown Source:28)
> 
> Following the log, this error wasn't made by the module.

Then maybe I gave you the wrong part of the locket but this was one of the error also what is the reason for this error if it is not because of the module?

**Comment by 1767523953** [comment]
> ~Same problem with MIUI.EU 12.5.5~ How can I disable this module when I can not use the launcher ?
> 
> My mistake, not the same problem.

delete the apk file of the module in Recovery
