### ISSUE TITLE
#bug Unlock Grid restrictions is not working

### ISSUE THREAD

**Issue by AadilGillani** [1767523953/MiuiHome#16]
![Screenshot_2021-09-21-22-32-01-902_com.miui.home.jpg](https://user-images.githubusercontent.com/15800642/134220471-7a807974-2f0d-4acb-a549-4a204b05dfde.jpg)![Screenshot_2021-09-21-22-39-50-176_com.miui.home.jpg](https://user-images.githubusercontent.com/15800642/134220478-260b0158-716c-4f50-b6df-083962605925.jpg)

This feature does not working 
Everything else is working fantastically thanks a lot.

**Comment by YuKongA** [comment]
The problem is known, but we don’t know how to fix it now.

**Comment by YuKongA** [comment]
Fixed it
